<?php $this->headTitle()->prepend($this->content->getTitle() . ' '); ?>
<h2><?php echo $this->content->getTitle(); ?></h2>
<p class="header-sub"><?php echo $this->content->getDate()->format('F j, Y'); ?></p>
<?php if (\Zend_Auth::getInstance()->hasIdentity()) : ?>
<div id="adminMenu" class="block">
    <p><a href="/blog/admin/edit/<?php echo $this->content->getId(); ?>/">Edit Article</a></p>
</div>
<?php endif; ?>

<p><?php echo $this->content->getContent(); ?></p>

<hr/>
<div id="disqus">
    <h3>Comments</h3>
    <div id="disqus_thread"></div>
    <script type="text/javascript">
       var disqus_identifier = <?php echo $this->content->getId(); ?>;
       var disqus_developer = true;

      (function() {
       var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
       dsq.src = 'http://theridgway.disqus.com/embed.js';
       (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
      })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript=theridgway">comments powered by Disqus.</a></noscript>
</div>