<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <meta http-equiv="Content-Language" content="en-us" />
    <?php echo $this->headTitle(); ?>

    <?php echo $this->headScript(); ?>

    <?php echo $this->headStyle(); ?>

</head>

<body>
    <div id="header">
        <?php echo $this->layout()->header; ?>

    </div>

    <div id="content">
        <?php echo $this->layout()->content; ?>

    </div>

    <div id="sidebar">
        <?php echo $this->layout()->sidebar; ?>

    </div>

    <div id="footer">
        <?php echo $this->layout()->footer; ?>

    </div>
</body>
</html>
