<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <meta http-equiv="Content-Language" content="en-us" />
    <?php echo $this->headTitle(); ?>

    
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.1.0/build/cssreset/reset-min.css" />
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.1.0/build/cssbase/base-min.css" />
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.1.0/build/cssfonts/fonts-min.css" />
    <link rel="stylesheet" type="text/css" media="screen" href="/themes/default/css/main.css" />
    <?php echo $this->headStyle(); ?>

    <script type="text/javascript" src="http://jqueryjs.googlecode.com/files/jquery-1.3.2.min.js"></script>
    <script type="text/javascript" src="/lib/js/ckeditor/ckeditor.js"></script>
    <script type="text/javascript" src="/lib/js/ckeditor/adapters/jquery.js"></script>
    <?php echo $this->headScript(); ?>

</head>

<body>
    <div id="wrapper">
        <?php echo $this->render('partials/header.phtml'); ?>
        
        
        <div id="top">
            <?php echo $this->layout()->top; ?>

        </div>

        <div id="body">
            <div id="main">
                <div id="content">
                    <?php echo $this->layout()->content; ?>

                </div>
            </div>

            <div id="sidebar">
                <?php echo $this->layout()->sidebar; ?>

            </div>
        </div>

        <div id="bottom">
            <?php echo $this->layout()->bottom; ?>

        </div>
        <?php echo $this->render('partials/footer.phtml'); ?>

        
    </div>
</body>
</html>
