        <a href="http://github.com/mridgway"><img style="position: absolute; top: 0; right: 0; border: 0;" src="http://s3.amazonaws.com/github/ribbons/forkme_right_gray_6d6d6d.png" alt="Fork me on GitHub" /></a>
        <div id="footer" class="grid_16">
            <p id="copyright">All content licensed under <a rel="license" href="http://creativecommons.org/licenses/by-sa/3.0/">Creative Commons Share-Alike 3.0</a>.</p>
        </div>
        <div class="clear"></div>