<p>I am Michael Ridgway, a PHP developer in Lancaster, PA. This is where I write articles covering topics in web development, databases, and whatever else I find interesting.</p>

<dl>
    <dt>Employment</dt>
    <dd>Web Developer @ <a href="http://www.mododesigngroup.com" target="_blank">Modo Design Group</a></dd>
</dl>

<dl>
    <dt>Development Environment</dt>
    <dd>Mac OSX (work)</dd>
    <dd>Ubuntu (home)</dd>
    <dd><a href="http://netbeans.org" target="_blank">NetBeans</a></dd>
    <dd>PHP 5.3 / <a href="http://framework.zend.com" target="_blank">Zend Framework</a> / <a href="http://www.doctrine-project.org" target="_blank">Doctrine 2</a></dd>
    <dd>MySQL 5</dd>
    <dd>JavaScript / JQuery / YUI 3</dd>
</dl>

<p class="button"><a href="#/about" title="Coming Soon">More About Me (Coming Soon)</a></p>