<?php

namespace Proxy;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class UserModelUserProxy extends \User\Model\User implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister);
            unset($this->_identifier);
        }
    }

    
    public function getRoleId()
    {
        $this->_load();
        return parent::getRoleId();
    }

    public function __get($name)
    {
        $this->_load();
        return parent::__get($name);
    }

    public function __isset($name)
    {
        $this->_load();
        return parent::__isset($name);
    }

    public function __set($name, $value)
    {
        $this->_load();
        return parent::__set($name, $value);
    }

    public function __call($name, $args)
    {
        $this->_load();
        return parent::__call($name, $args);
    }

    public function setter($variable)
    {
        $this->_load();
        return parent::setter($variable);
    }

    public function getter($variable)
    {
        $this->_load();
        return parent::getter($variable);
    }

    public function getRepository()
    {
        $this->_load();
        return parent::getRepository();
    }


    public function __sleep()
    {
        if (!$this->__isInitialized__) {
            throw new \RuntimeException("Not fully loaded proxy can not be serialized.");
        }
        return array('id', 'email', 'firstName', 'lastName');
    }
}